package com.coppersmith.music1chat

object GenreData {
    val MAJOR_GENRES = listOf(
        "60s",
        "70s",
        "80s",
        "90s",
        "Alternative",
        "Ambient",
        "Americana",
        "Big Band",
        "Bluegrass",
        "Blues",
        "Celtic",
        "Chillout",
        "Christian",
        "Classical",
        "College",
        "Comedy",
        "Country",
        "Dance",
        "Disco",
        "Electronic",
        "Folk",
        "Funk",
        "Gospel",
        "Hawaiian",
        "Hip Hop",
        "House",
        "Indie",
        "Jazz",
        "K-Pop",
        "Latin",
        "Lounge",
        "Metal",
        "News",
        "Oldies",
        "Opera",
        "Piano",
        "Pop",
        "Public",
        "Punk",
        "Reggae",
        "Relaxation",
        "Rock",
        "Smooth Jazz",
        "Soul",
        "Soundtrack",
        "St Louis",
        "Swing",
        "Talk",
        "Techno",
        "Trance",
        "World"
    ).sorted()
}